# fixing parse error
sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dimashok/docker-react -f Dockerfile.dev .

  script:
  - docker run -e CI=true dimashok/docker-react npm run test