sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dimashok/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dimashok/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "dp_docker-react"
  env: "Dpdockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-168937149820"
  bucket_path: "dp_docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"