version: '3'

# Essentially, replaces the "run" command below
#   > docker run -it -p 3000:3000 -v /app/node_modules -v ~/frontend:/app dimashok:frontend
services: 
    web:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - .:/app
    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "test"]